services:
  app:
    container_name: nest-lab-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/api
      - /usr/src/app/node_modules
    command: npm run start:prod
    networks:
      - laboratorio-network
    depends_on:
      - nest_lab_db

  nest_lab_db:
    image: mysql:8.0
    container_name: mysql-nest-lab
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestlab
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - laboratorio-network
    volumes:
      - mysql_lab_data:/var/lib/mysql
  
  nest_lab_phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-nest-lab
    restart: unless-stopped
    environment:
      PMA_HOST: nest_lab_db
      PMA_PORT: 3306
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8844:80"
    networks:
      - laboratorio-network
    depends_on:
      - nest_lab_db
volumes:
  mysql_lab_data:
    driver: local

networks:
  laboratorio-network:
    driver: bridge